### ISSUE TITLE
Can not still google

### ISSUE THREAD

**Issue by Leser2020** [freefq/tutorials#14]
does anybody work?

**Comment by freefq** [comment]
这标题是中文谷歌翻译过来的吗？

如何快速的选择有效节点？
批量选中导入节点（可以Ctrl+a），右键菜单中选择测试服务器真连接延迟（快捷键是Ctrl+r），从测试结果中选择延迟比较低的节点设为活动服务器（Enter）。

**Comment by Leser2020** [comment]
还是一样，选择了一个，google上不了

**Comment by Leser2020** [comment]
![image](https://user-images.githubusercontent.com/27276258/131209889-3f82e5fe-fa04-4c77-8ab2-a9b0ffbc4285.png)

**Comment by Leser2020** [comment]
![test](https://user-images.githubusercontent.com/27276258/131235318-6bb07a53-0707-4f18-b1a4-fd0eee2f07da.PNG)

**Comment by LL0626** [comment]
???





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "freefq/tutorials"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月29日(星期天) 上午9:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [freefq/tutorials] Can not still google (#14)





 

 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LL0626** [comment]
使用前先测试一下服务器 还有要点击订阅 每天的服务器状态都不一样




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "freefq/tutorials"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月28日(星期六) 下午3:11
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [freefq/tutorials] Can not still google (#14)





 

 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Leser2020** [comment]
好像chrome有点问题，使用ie是好的，不确定是不是哪里设置的

**Comment by Leser2020** [comment]
找到了，是之前安装的一个VPN的插件导致的，现在ok了
